POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "DOT.SignRawTx",
	"params": [{
		"entropy": "1EE60AB0A1AA13565CFE05866275A7B0A9074E445F447D038818EF41501C80ED",
		"seed": "",
		"m1": 20202064,
		"m2": 0,
		"toAddress": "14fhaZ3cheqqeKZ9wa6EGYxbaEcSEqsyWawFLPzs8N9h7tyT",
		"amount": "1500000",
		"nonce": "0",
		"fee": "1"
		}]
}
