POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "BCH.AddressValidate",
	"params": [{
		"address": "qrmk58aupd7fefgld9hn495cd7e2d0nqeym92evt20",
		"mainnet": true
		}]
}
