POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "ETH.EntropyToAddress",
	"params": [{
		"entropy": "7dfe828a0d2755bf7c8c2c4f1949aad888e05fbecd726ae4c7ea4b3fdfcc113f",
		"seed": "",
		"m1": 20202025,
		"m2": 0,
		"count": 3
		}]
}
