POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "BSV.CreateRawTx",
	"params": [{
		"mainnet": true,
		"inputs": [{"txid":"86fdd127ed175dc28efb4906c42cd7e525f052afcf6592c4730f4d4f53a8faed","vout":0}],
		"amounts": {"19EXwtZT8emnTeopozh7Y2YQEkLCJ8fbsB":0.001,"1JgasYbPWEpQr7LWd3bDhJ7AwYeKFWt6tf":0.10649}
		}]
}
