POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "BTC.EntropyToAddress",
	"params": [{
		"entropy": "283FEE7022277C9566CDBF6B85A5D016986E0CAE555797858AACC672A3427570",
		"seed": "",
		"m1": 20202025,
		"m2": 0,
		"count": 55,
		"compresspubkey": true,
		"mainnet": true
		}]
}
