POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "ENTROPY.EntropyFromMnemonic",
	"params": [{
		"mnem": "law village penalty bottom inspire text vendor machine excuse ski height rain mix cool will purity helmet change whisper nose worth toward eager today"
		}]
}
