POST https://127.0.0.1:34911/ HTTP/1.1
content-type: application/json

{
	"id": 1,
	"method": "BCH.AddressValidate",
	"params": [{
		"address": "qpvdse9p5rmr2jm08vmfrqg37vwuz4ylgs3lnun5hv",
		"mainnet": true
		}]
}
